export const ALL_WORK_REQUEST = "ALL_WORK_REQUEST";
export const ALL_WORK_SUCCESS = "ALL_WORK_SUCCESS";
export const ALL_WORK_FAIL = "ALL_WORK_FAIL";

export const UPDATE_SUCCESS = "UPDATE_SUCCESS";
export const UPDATE_FAIL = "UPDATE_FAIL";

export const UPDATE_NAME_SUCCESS = "UPDATE_NAME_SUCCESS";
export const UPDATE_NAME_FAIL = "UPDATE_NAME_FAIL";

export const ADD_WORK_SUCCESS = "ADD_WORK_SUCCESS";
export const ADD_WORK_FAIL = "ADD_WORK_FAIL";

export const REMOVE_WORK_SUCCESS = "REMOVE_WORK_SUCCESS";
export const REMOVE_WORK_FAIL = "REMOVE_WORK_FAIL";
